export const default_category = [
  {title: '全部', value: 0},
  {title: '女装', value: 1},
  {title: '男装', value: 2},
  {title: '内衣', value: 3},
  {title: '美妆', value: 4},
  {title: '配饰', value: 5},
  {title: '鞋品', value: 6},
  {title: '箱包', value: 7},
  {title: '儿童', value: 8},
  {title: '母婴', value: 9},
  {title: '居家', value: 10},
  {title: '美食', value: 11},
  {title: '数码', value: 12},
  {title: '家电', value: 13},
  {title: '车品', value: 15},
  {title: '文体', value: 16},
  {title: '宠物', value: 17},
  {title: '其他', value: 14},
];

export const default_category2 = [
  {title: '母婴童品', value: 1},
  {title: '百变女装', value: 2},
  {title: '食品酒水', value: 3},
  {title: '居家日用', value: 4},
  {title: '美妆洗护', value: 5},
  {title: '品质男装', value: 6},
  {title: '舒适内衣', value: 7},
  {title: '箱包配饰', value: 8},
  {title: '男女鞋靴', value: 9},
  {title: '宠物用品', value: 10},
  {title: '数码家电', value: 11},
  {title: '车品文体', value: 12},
];
